blog/urls.py
from django.urls import path, re_path
from .views import PostListView, PostDetailView, PostCategoryListView, redirect_to_blog_home, search_view

app_name = 'blog'
urlpatterns = [
    path('search/', search_view, name="search"),
    path('category', redirect_to_blog_home, name="redirect-to-blog-home"),
    path('', PostListView.as_view(), name="blog-index"),
    path('post/<slug>', PostDetailView.as_view(), name="blog-detail"),
    path('category/<slug>', PostCategoryListView.as_view(), name="blog-category-list"),
    re_path(r'^category(\/){0,1}', redirect_to_blog_home, name="redirect-to-blog-home")
]

conf/urls.py
from django.conf.urls import url, re_path
from django.conf.urls.i18n import i18n_patterns
from core.services.urlresolvers import solid_i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

urlpatterns = solid_i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    prefix_default_language=False
)

urlpatterns += solid_i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
    path('core', include('core.urls')),
    prefix_default_language=False
    # path('services/', include('services.urls')),
    # path('gallery/', include('portfolio.urls')),
    # path('blog/', include('blog.urls'))
)

if settings.DEBUG:
    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import contact_us_view


def dummy():
    pass


app_name = 'core'
urlpatterns = [
    path('contact-us', contact_us_view, name="contact-us"),
    path('search', dummy, name="search")
]

blog/models.py
from djangocms_text_ckeditor.fields import HTMLField
from cms.models.pluginmodel import CMSPlugin
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from filer.fields.image import FilerImageField
from re import compile, sub


class Category(models.Model):
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=55
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        null=True,
        blank=True
    )
    # Seo
    h1_title = models.CharField(
        verbose_name=_('H1 Title'),
        max_length=255,
        null=True,
        blank=True
    )
    page_title = models.CharField(
        verbose_name=_('Seo Page Title'),
        max_length=255,
        null=True,
        blank=True
    )
    meta_description = models.TextField(
        verbose_name=_('Meta Description'),
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('blog:blog-category-list', kwargs={
            'slug': self.slug
        })

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Post(models.Model):
    category = models.ForeignKey(
        to="Category",
        verbose_name=_('Category'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        verbose_name=_('Author'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=1

    )
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=155
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        null=True,
        blank=True
    )
    image = FilerImageField(
        verbose_name=_('Image'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    body = HTMLField(
        verbose_name=_('Content'),
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        verbose_name=_('Created Date'),
        auto_now_add=True
    )
    updated = models.DateTimeField(
        verbose_name=_('Last Update'),
        auto_now=True
    )

    # Seo
    h1_title = models.CharField(
        verbose_name=_('H1 Title'),
        max_length=255,
        null=True,
        blank=True
    )
    page_title = models.CharField(
        verbose_name=_('Seo Page Title'),
        max_length=255,
        null=True,
        blank=True
    )
    meta_description = models.TextField(
        verbose_name=_('Meta Description'),
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('blog:blog-detail', kwargs={
            "slug": self.slug
        })

    def get_teaser_description(self):
        text = self.body
        cleanr = compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
        result = sub(cleanr, '', text)
        return f"{result[:355]}[...]"

    def get_next_post(self):
        next_post_id = self.id + 1
        next_post = Post.objects.filter(id=next_post_id).first()
        return reverse('blog:blog-detail', kwargs={
                "slug": next_post.slug
            }) if next_post else 'javascript:void(0)'

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class BlogRecentItemPluginModel(CMSPlugin):
    post = models.ForeignKey(
        to="Post",
        on_delete=models.SET_NULL,
        null=True,
    )

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from core.utils import get_full_context, get_page_seo
from .models import Post, Category


class BaseListView(ListView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        context = get_full_context(context)
        return context


class PostListView(BaseListView):
    template_name = 'blog/pages/post-list.html'
    paginate_by = 10
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context = get_full_context(context)
        context['page'] = get_page_seo(slug='blog')
        return context

    def get_queryset(self):
        return super().get_queryset().select_related('author').select_related('category').prefetch_related('image')


class PostDetailView(DetailView):
    template_name = 'blog/pages/post-detail.html'
    model = Post

    def get_queryset(self):
        return super().get_queryset().select_related('category').select_related('author')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        context = get_full_context(context)
        return context


class PostCategoryListView(BaseListView):
    template_name = 'blog/pages/post-list.html'
    paginate_by = 10
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context = get_full_context(context)
        return context

    def get_queryset(self):
        if self.kwargs['slug'] != 'uncategorized':
            return super().get_queryset().filter(category__slug=self.kwargs['slug'])
        else:
            return super().get_queryset().filter(category__isnull=True)


def search_view(request):
    if request.GET:
        query_string = request.GET['s']
        if len(query_string) <= 0:
            return redirect('blog:blog-index')
        queryset = Post.objects.filter(name__icontains=query_string)
        queryset |= Post.objects.filter(category__name__icontains=query_string)
        queryset |= Post.objects.filter(body__icontains=query_string)

        context = {
            'post_list': queryset,
            'categories': Category.objects.all()
        }
        context = get_full_context(context)
        return render(request, 'blog/pages/post-list.html', context)

    else:
        return redirect('blog:blog-index')


def redirect_to_blog_home(request, regex=None):
    return redirect('blog:blog-index')

blog/templates/blog/pages/post-detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block banner_image %}{% static 'blog/img/title_bg_02.jpg' %}{% endblock %}
{% block blog_content %}
    <div class="fl-container hasRS" style="padding-top: 90px">
       <div class="row">
          <div class="posts-block ">
             <div class="contentarea single_content single_page single_post">
                <div class="pf_output_container pf_tag_ post_has_image "><img width="1170" height="740" src="{{ post.image.url }}" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="" loading="lazy"></div>
                <div class="preview_top_wrapper single_top_wrapper">
                   <div class="post_meta">
                      <div class="meta-item">{{ post.created }}</div>
                      <div class="meta-item"><a href="javascript:void(0)">{{ post.author.first_name }}</a></div>
                    <div class="meta-item"><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></div>
                   </div>
                   <!-- .post_meta -->
                   <h1 class="blog_post_title">{{ post.name }}</h1>
                </div>
                <!-- .preview_top_wrapper -->
                <article class="contentarea single_contentarea">
                   <h3 class="hidden">{{ post.name }}</h3>
                   {% autoescape off %}
                       {{ post.body }}
                   {% endautoescape %}
                </article>
                <div class="single_post_ground">
                   <div class="author_info">
                      <div class="author_ava">
                         <img alt="" src="" class="avatar avatar-220 photo" height="220" width="220" loading="lazy">
                      </div>
                      <div class="author_content">
                         <div class="author_name">
                            <h6>John</h6>
                         </div>
                         Sed vitae ante aliquet, vehicula lorem ac, vulputate odio. Pellentesque sit amet augue quis ipsum finibus facilisis eget vitae sem.
                      </div>
                   </div>
                   <div class="single_prev_next_buttons">
                      <div class="fright"><a href="{{ post.get_next_post }}" rel="prev">Next</a></div>
                   </div>
                </div>
    {#            <div class="row">#}
    {#               <div class="span12">#}
    {#                  <div id="respond" class="comment-respond">#}
    {#                     <h3 id="reply-title" class="comment-reply-title">Leave a Comment <small><a rel="nofollow" id="cancel-comment-reply-link" href="/wp/md/browcraft/2018/03/21/permanent-makeup-methods/#respond" style="display:none;">Cancel reply</a></small></h3>#}
    {#                     You must be logged in to post a comment.#}
    {#                  </div>#}
    {#                  <!-- #respond -->#}
    {#               </div>#}
    {#            </div>#}
             </div>
             <!-- .contentarea -->
          </div>
       </div>
    </div>
{% endblock %}

blog/templates/blog/pages/post-list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block banner_image %}{% static 'blog/img/title_bg_02.jpg' %}{% endblock %}

{% block blog_content %}
        <div class="fl-container hasRS">
            <div class="posts-block ">
                <div class="contentarea">
                    <div class="vc_row wpb_row vc_row-fluid vc_custom_1488792104548">
                        <div class="wpb_column vc_column_container vc_col-sm-12">
                            <div class="vc_column-inner">
                                <div class="wpb_wrapper">
                                    <div class="gt3_blog_listing  ">
                                        {% if post_list %}
                                            {% for post in post_list %}
                                                {% include 'blog/components/post-teaser.html' %}
                                            {% endfor %}
                                        {% else %}
                                            No posts for this category yet... You can
                                            <a href="{% url 'core:contact-us' %}">fill out the form</a> and
                                            we'll contact with you as soon as possible for more consultation.
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clea_r"></div>
                    <div class="clea_r"></div>
                </div>
            </div>
        </div>
{% endblock %}