blog/urls.py
from django.urls import path, re_path
from .views import PostListView, PostDetailView, PostCategoryListView, redirect_to_blog_home, search_view

app_name = 'blog'
urlpatterns = [
    path('search/', search_view, name="search"),
    path('category', redirect_to_blog_home, name="redirect-to-blog-home"),
    path('', PostListView.as_view(), name="blog-index"),
    path('post/<slug>', PostDetailView.as_view(), name="blog-detail"),
    path('category/<slug>', PostCategoryListView.as_view(), name="blog-category-list"),
    re_path(r'^category(\/){0,1}', redirect_to_blog_home, name="redirect-to-blog-home")
]

conf/urls.py
from django.conf.urls import url, re_path
from django.conf.urls.i18n import i18n_patterns
from core.services.urlresolvers import solid_i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

urlpatterns = solid_i18n_patterns(
    re_path(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    prefix_default_language=False
)

urlpatterns += solid_i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
    path('core', include('core.urls')),
    prefix_default_language=False
    # path('services/', include('services.urls')),
    # path('gallery/', include('portfolio.urls')),
    # path('blog/', include('blog.urls'))
)

if settings.DEBUG:
    urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from djangocms_text_ckeditor.fields import HTMLField
from cms.models.pluginmodel import CMSPlugin
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from filer.fields.image import FilerImageField
from re import compile, sub


class Category(models.Model):
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=55
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        null=True,
        blank=True
    )
    # Seo
    h1_title = models.CharField(
        verbose_name=_('H1 Title'),
        max_length=255,
        null=True,
        blank=True
    )
    page_title = models.CharField(
        verbose_name=_('Seo Page Title'),
        max_length=255,
        null=True,
        blank=True
    )
    meta_description = models.TextField(
        verbose_name=_('Meta Description'),
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('blog:blog-category-list', kwargs={
            'slug': self.slug
        })

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class Post(models.Model):
    category = models.ForeignKey(
        to="Category",
        verbose_name=_('Category'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    author = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        verbose_name=_('Author'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=1

    )
    name = models.CharField(
        verbose_name=_('Name'),
        max_length=155
    )
    slug = models.SlugField(
        verbose_name=_('Slug'),
        null=True,
        blank=True
    )
    image = FilerImageField(
        verbose_name=_('Image'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    body = HTMLField(
        verbose_name=_('Content'),
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        verbose_name=_('Created Date'),
        auto_now_add=True
    )
    updated = models.DateTimeField(
        verbose_name=_('Last Update'),
        auto_now=True
    )

    # Seo
    h1_title = models.CharField(
        verbose_name=_('H1 Title'),
        max_length=255,
        null=True,
        blank=True
    )
    page_title = models.CharField(
        verbose_name=_('Seo Page Title'),
        max_length=255,
        null=True,
        blank=True
    )
    meta_description = models.TextField(
        verbose_name=_('Meta Description'),
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('blog:blog-detail', kwargs={
            "slug": self.slug
        })

    def get_teaser_description(self):
        text = self.body
        cleanr = compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
        result = sub(cleanr, '', text)
        return f"{result[:355]}[...]"

    def get_next_post(self):
        next_post_id = self.id + 1
        next_post = Post.objects.filter(id=next_post_id).first()
        return reverse('blog:blog-detail', kwargs={
                "slug": next_post.slug
            }) if next_post else 'javascript:void(0)'

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class BlogRecentItemPluginModel(CMSPlugin):
    post = models.ForeignKey(
        to="Post",
        on_delete=models.SET_NULL,
        null=True,
    )

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from core.utils import get_full_context, get_page_seo
from .models import Post, Category


class BaseListView(ListView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        context = get_full_context(context)
        return context


class PostListView(BaseListView):
    template_name = 'blog/pages/post-list.html'
    paginate_by = 10
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context = get_full_context(context)
        context['page'] = get_page_seo(slug='blog')
        return context

    def get_queryset(self):
        return super().get_queryset().select_related('author').select_related('category').prefetch_related('image')


class PostDetailView(DetailView):
    template_name = 'blog/pages/post-detail.html'
    model = Post

    def get_queryset(self):
        return super().get_queryset().select_related('category').select_related('author')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        context = get_full_context(context)
        return context


class PostCategoryListView(BaseListView):
    template_name = 'blog/pages/post-list.html'
    paginate_by = 10
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context = get_full_context(context)
        return context

    def get_queryset(self):
        if self.kwargs['slug'] != 'uncategorized':
            return super().get_queryset().filter(category__slug=self.kwargs['slug'])
        else:
            return super().get_queryset().filter(category__isnull=True)


def search_view(request):
    if request.GET:
        query_string = request.GET['s']
        if len(query_string) <= 0:
            return redirect('blog:blog-index')
        queryset = Post.objects.filter(name__icontains=query_string)
        queryset |= Post.objects.filter(category__name__icontains=query_string)
        queryset |= Post.objects.filter(body__icontains=query_string)

        context = {
            'post_list': queryset,
            'categories': Category.objects.all()
        }
        context = get_full_context(context)
        return render(request, 'blog/pages/post-list.html', context)

    else:
        return redirect('blog:blog-index')


def redirect_to_blog_home(request, regex=None):
    return redirect('blog:blog-index')

blog/templates/blog/components/post-teaser.html
<div class="blog_post_preview standart_post ">
    <div class="preview_content">
        <div class="pf_output_container pf_tag_ post_has_image "><img width="1170" height="740" src="{{ post.image.url }}" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt=""></div>
        <div class="preview_top_wrapper">
            <div class="post_meta">
                <div class="meta-item">{{ post.created }}</div>
                <div class="meta-item"><a href="javascript:void(0)">{{ post.author.first_name }}</a></div>
                <div class="meta-item"><a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></div>
{#                <div class="meta-item"><a href="#respond">0 Comments</a></div>#}
            </div>
            <!-- .post_meta -->
            <div class="post_title">
                <div class="blog_listing_title"><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></div>
            </div>
            <!-- .page_title -->
        </div>
        <article class="contentarea">
            <h3 class="hidden">{{ post.title }}</h3>{{ post.get_teaser_description }}</article>
        <div class="post_footer">
            <div class="post_footer_lp"> <a href="{{ post.get_absolute_url }}" class="preview_read_more shortcode_button"><span>read more</span></a> </div>
            <div class="clear"></div>
        </div>
        <!-- .post_footer -->
    </div>
</div>

blog/templates/blog/components/recent-posts-item.html
<div class="gt3_related_post_item">
    <div class="gt3_related_post_item_inner" data-pad="0px">
        <a href="javascript:void(0)"
           class="gt3_related_post_link">
            <img class="gt3_related_image"
                 src="{{ instance.post.image.url }}"
                 alt="{{ instance.post.image.alt_text }}">
            <div class="gt3_prelated_overlay"></div>
            <div class="gt3_related_content">
                <div class="gt3_related_title">{{ instance.post.name }}</div>
                <div class="gt3_related_date">
                    {{ instance.post.created }}
                </div>
            </div>
        </a>

    </div>
</div>

blog/templates/blog/components/recent-posts.html
{% load cms_tags %}
<div data-vc-full-width="true" data-vc-full-width-init="true"
     data-vc-stretch-content="true"
     class="vc_row wpb_row vc_row-fluid vc_row-no-padding"
     style="position: relative; left: -190px; box-sizing: border-box; width: 1580px;">
    <div class="wpb_animate_when_almost_visible wpb_fadeIn fadeIn wpb_column vc_column_container vc_col-sm-12">
        <div class="vc_column-inner vc_custom_1520329428516">
            <div class="wpb_wrapper">
                <div class="gt3_related_posts_module   vc_custom_1521030356606">

                    <div class="gt3_related_posts_wrapper">
                        <div class="gt3_related_posts items_3" data-pad="0px">
                            {% for child_plugin_instance in instance.child_plugin_instances %}
                                {% render_plugin child_plugin_instance %}
                            {% endfor %}
{#                            <div class="gt3_related_post_item">#}
{#                                <div class="gt3_related_post_item_inner" data-pad="0px"#}
{#                                     style="padding-left: 0px;">#}
{#                                    <a href="javascript:void(0)"#}
{#                                       class="gt3_related_post_link">#}
{#                                        <img class="gt3_related_image"#}
{#                                             src="{% static 'core/img/blog_img_04-800x580.jpg' %}"#}
{#                                             alt="related_image">#}
{#                                        <div class="gt3_prelated_overlay"></div>#}
{#                                        <div class="gt3_related_content">#}
{#                                            <div class="gt3_related_title">What is#}
{#                                                Microblading?#}
{#                                            </div>#}
{#                                            <div class="gt3_related_date">#}
{#                                                March 21, 2018#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </a>#}
{##}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="gt3_related_post_item">#}
{#                                <div class="gt3_related_post_item_inner" data-pad="0px"#}
{#                                     style="padding-left: 0px;">#}
{#                                    <a href="javascript:void(0)"#}
{#                                       class="gt3_related_post_link">#}
{#                                        <img class="gt3_related_image"#}
{#                                             src="{% static 'core/img/blog_img-1-800x580.jpg' %}"#}
{#                                             alt="related_image">#}
{#                                        <div class="gt3_prelated_overlay"></div>#}
{#                                        <div class="gt3_related_content">#}
{#                                            <div class="gt3_related_title">Permanent#}
{#                                                Makeup Methods#}
{#                                            </div>#}
{#                                            <div class="gt3_related_date">#}
{#                                                March 21, 2018#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </a>#}
{##}
{#                                </div>#}
{#                            </div>#}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row-full-width vc_clearfix"></div>

blog/templates/blog/components/sidebar.html
{% load static cache %}
<div class="right-sidebar-block">
    <div class="sidepanel widget_text">
        <div class="textwidget">
            <p>
                <img loading="lazy" class="rounded size-full wp-image-2435 aligncenter" style="margin-bottom: 0" src="{% static 'blog/img/img_sidebar_01.jpg' %}" alt="" width="150" height="150">
                <br> Brofcraft offers a wide array of eyebrow and skin care treatments using world renowned techniques
            </p>
            <div class="gt3_social" style="text-align: center">
                <a style="color: #7aafea" href="javascript:void(0)">TW</a>
                <a style="color: #122d71" href="javascript:void(0)">FB</a>
                <a style="color: #ba0a0a" href="javascript:void(0)">PN</a>
            </div>
        </div>
    </div>
    <div class="sidepanel widget_search">
        <form name="search_form" method="GET" action="{% url 'blog:search' %}" class="search_form">
            <input type="text" name="s" placeholder="Search">
            <div class="gt3_form_button_wrapper"><span><input type="submit" value="Search"></span></div>
        </form>
    </div>
    {% cache 84000 categories %}
        <div class="sidepanel widget_categories">
            <h6 class="widget_title">Categories</h6>
            <ul>
                {% for blog_category in categories %}
                    <li class="cat-item cat-item-{{ forloop.counter }}"><a href="{{ blog_category.get_absolute_url }}">{{ blog_category.name }}</a> </li>
                {% endfor %}
                <li class="cat-item"><a href="{% url 'blog:blog-category-list' 'uncategorized' %}">Uncategorized</a> </li>
            </ul>
        </div>
    {% endcache %}
</div>